version: '3'

services:

  project:
    build: .
    volumes:
      - ./project:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
    restart: always

  nginx:
    image: nginx
    ports:
      - '2222:80'
    volumes:
      - ./.nginx:/etc/nginx/conf.d
    restart: always

  mysql:
    image: mysql
    ports:
      - '3333:3306'
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    restart: always
  